---
name: "CITests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  citests:
    name: CI-Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
          submodules: 'recursive'

      - run: |
          sudo apt-get install -y libssl-dev
          cmake -S . -B build -DPICOQUIC_FETCH_PTLS:BOOL=ON
          cmake --build build

      - name: Perform Unit Tests
        run: |
            ulimit -c unlimited -S
            build/picoquic_ct -n -r && QUICRESULT=$?
            build/picohttp_ct -n -r -x http_corrupt && HTTPRESULT=$?
            if [[ ${QUICRESULT} == 0 ]] && [[ ${HTTPRESULT} == 0 ]]; then exit 0; fi;
            exit 1
