---
name: "CITests"

on:
  push

jobs:
  citests:
    name: CI-Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
          submodules: 'recursive'

      - run: |
          sudo apt-get install -y libssl-dev
          ./ci/build_picotls.sh
          mkdir build
          cd build
          cmake ..
          cmake --build .
          make

      - name: Perform Unit Tests
        run: |
            cd build
            ulimit -c unlimited -S
            ./picoquic_ct -n -r && QUICRESULT=$?
            ./picohttp_ct -n -r -x http_corrupt && HTTPRESULT=$?
            if [[ ${QUICRESULT} != 0 ]]; then for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd)/picoquic_ct core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done; fi;
            if [[ ${HTTPRESULT} != 0 ]]; then for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd)/picohttp_ct core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done; fi;
            if [[ ${QUICRESULT} == 0 ]] && [[ ${HTTPRESULT} == 0 ]]; then exit 0; fi;
            exit 1